name: middilook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  # camera: ^0.9.4+5
  simple_circular_progress_bar: ^1.0.2
  smooth_page_indicator: ^1.0.2
  showcaseview: ^2.0.3
  shared_preferences: ^2.2.0
  get: ^4.6.5
  otp_text_field: ^1.1.1
  image_picker: ^0.8.7
  flutter_cache_manager: ^3.3.0
  video_player: ^2.6.0
  preload_page_view: ^0.2.0
  visibility_detector: ^0.4.0+2
  video_trimmer: ^2.0.0
  url_launcher: ^6.0.9
  flutter_native_splash: ^2.2.4
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.15
  firebase_auth: ^4.2.10
  video_compress: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/logo_icon_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: "lib/assets/splash_icon.png"
  android_12:
    image: "lib/assets/splash_icon.png"