name: middilook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  # camera: ^0.9.4+5
  get: ^4.6.5
  image_picker: ^0.8.7
  video_player: ^2.6.0
  url_launcher: ^6.0.9
  flutter_launcher_icons: ^0.9.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
